Equipment Management Epic
tranleduyan/ETC-Frontend pull request #13
Opened 2024-02-24 17:30 UTC by tranleduyan

This PR covers:
1. ER-122: Implement Equipment Addition API Calls
2. ER-169: Implement Get All Equipments API Calls
3. ER-154: Implement Mass Delete Equipment API Calls
4. ER-138: Skeleton Equipment Details Page Layout
5. ER-168: Implement Equipment Details API Calls
6. ER-136: Skeleton Update Equipment Page Layout
7. ER-143: Implement Update Equipment API Calls
8. ER-137: Skeleton Update Type Page Layout
9. ER-141: Implement Update Type API Calls
10. ER-139: Skeleton Update Model Page Layout
11. ER-142: Implement Update Model API Calls

The features in this PR:
- Mass Delete Equipment
- View Equipment Details
- Edit/Update Equipment
- Edit/Update Type
- Edit/Update Model
- Hide RFID features in Dashboard for prod.

2024-03-01 04:27 UTC, mohammedking11-spu approved these changes
Once again, great job Le, always amazed on how good and organized your code is. It follows the code convention thoroughly. I have tested it, and it works for: 

* Mass Delete Equipment ✅ 
* View Equipment Details ✅ 
* Edit/Update Equipment ✅ 
* Edit/Update Type ✅ 
* Edit/Update Model ✅ 

All in all, I have approved it, and great job once again Le!

2024-03-01 04:27 UTC, mohammedking11-spu commented on src/Components/Cards/EquipmentInventoryCard/EquipmentInventoryCard.js
Code looks clean and is written in a way that follows the code convention.

2024-03-01 04:27 UTC, mohammedking11-spu commented on src/Components/Cards/InventoryTypeSummaryCard/EquipmentTypeSummaryCard.js
> +      {/* TODO: ${isSelected ?  'EquipmentTypeSummaryCard-Active' : ''} when implement RFID equipment reserved*/}
Is this TODO also for future use?

2024-03-01 04:27 UTC, mohammedking11-spu commented on src/Components/Forms/EquipmentForm/EquipmentForm.js
Code looks clean and easy to follow.

2024-03-01 04:27 UTC, mohammedking11-spu commented on src/Components/Forms/ModelForm/ModelForm.js
Comments made it easy to follow 😁

2024-03-01 04:27 UTC, mohammedking11-spu commented on src/Components/Forms/TypeForm/TypeForm.js
Easy to follow, good job Le!

2024-03-01 04:27 UTC, mohammedking11-spu commented on src/Components/InputFields/DatePickerInputField/DatePickerInputField.js
Very nicely done.

2024-03-01 04:27 UTC, mohammedking11-spu commented on src/Pages/AddToInventoryPage/AddToInventoryPage.js
I really like how this is organized.

2024-03-01 04:27 UTC, mohammedking11-spu commented on src/Pages/EquipmentDetailsPage/EquipmentDetailsPage.js
Makes sense and looks good.

2024-03-04 02:36 UTC, YiJiePV requested changes
Looking good! Just some little things here and there I caught while reading through the changes. I also ran into a couple things while running and testing the code, but otherwise, I think these features are good to go!

2024-03-04 02:36 UTC, YiJiePV commented on src/Components/Cards/InventoryTypeSummaryCard/EquipmentTypeSummaryCard.js
> +  // eslint-disable-next-line
wait, what does this comment mean?

2024-03-04 02:36 UTC, YiJiePV commented on src/Components/Cards/InventoryTypeSummaryCard/EquipmentTypeSummaryCard.js
>    // Determine whether to use 'item' or 'items' based on the inventory amount
you'll probably want to update this comment ;)

2024-03-04 02:36 UTC, YiJiePV commented on src/Components/Dashboards/AdminDashboard/AdminDashboard.js
> +AdminDashboard.propTypes = {
nit: I think a little comment here would be nice

2024-03-04 02:36 UTC, YiJiePV commented on src/Components/Forms/EquipmentForm/EquipmentForm.css
>  }
nit: missing newline

2024-03-04 02:36 UTC, YiJiePV commented on src/Components/InputFields/DatePickerInputField/DatePickerInputField.js
> +DatePickerInputField.defaultProps = {
nit: comment?

2024-03-04 02:36 UTC, YiJiePV commented on src/Components/InputFields/DatePickerInputField/DatePickerInputField.js
> +export default DatePickerInputField;
nit: newline?

2024-03-04 02:36 UTC, YiJiePV commented on src/Components/Inventory/EquipmentInventory/EquipmentInventory.css
>  }
nit: newline?

2024-03-04 02:36 UTC, YiJiePV commented on src/Components/Inventory/ModelInventory/ModelInventory.css
>  }
nit: newline?

2024-03-04 02:36 UTC, YiJiePV commented on src/Components/Inventory/TypeInventory/TypeInventory.css
>  }
nit: newline?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/EquipmentDetailsPage/EquipmentDetailsPage.js
> +  useEffect(() => {
nit: comment?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.css
> +}
nit: newline?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateEquipmentPage/index.js
> +export { default } from './UpdateEquipmentPage';
nit: newline?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateModelPage/UpdateModelPage.css
> +}
nit: newline?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateTypePage/UpdateTypePage.css
> +}
nit: newline?

2024-03-04 02:36 UTC, YiJiePV commented on package.json
For some reason I got
![npm-problem](https://github.com/tranleduyan/ETC-Frontend/assets/97055517/59391c17-0365-477b-961d-6539acefde9a)

And here's the diagnosis from `npm audit`
![npm-rix](https://github.com/tranleduyan/ETC-Frontend/assets/97055517/e9773e0b-f01a-49ef-b1ab-ee4f6969780d)
![npm-fix](https://github.com/tranleduyan/ETC-Frontend/assets/97055517/6ff2c5a5-a8c8-4872-b995-3cc8b7b6ae03)

I did try running `npm audit fix --force` a few times, but that didn't completely solve this problem.

2024-03-04 02:36 UTC, YiJiePV commented on package-lock.json
I don't know if it's just me, but it took a while (at least 20-30 sec) for the app to boot up after I started it with `npm start`. It also gave me these warnings:
![npm-warnings](https://github.com/tranleduyan/ETC-Frontend/assets/97055517/289c7b83-6477-4643-b751-1f8d5e6a8ce5)
It might just be me since I tried using `npm audit fix --force` to fix package vulnerabilities.

2024-03-04 02:36 UTC, YiJiePV commented on src/Components/Cards/EquipmentInventoryCard/EquipmentInventoryCard.css
nit: idk if you noticed, but there's a newline missing at the end of the file ;)

2024-03-04 02:36 UTC, YiJiePV commented on src/Components/Cards/InventoryTypeSummaryCard/EquipmentTypeSummaryCard.js
>    const { className, typeID, typeName, inventoryAmount, reservationAmount, isSelected, OnEquipmentTypeSummaryCardClick } = props;
Are `typeID` and `isSelected` going to be used sometime?

2024-03-04 02:36 UTC, YiJiePV commented on src/Constants.js
>  export const OPTIONS = {
nit: comments?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/AddToInventoryPage/AddToInventoryPage.js
> +        .then(response => {
Are you going to use `response` here? I think there are a couple other unused `response`s here as well.

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/EquipmentDetailsPage/EquipmentDetailsPage.js
> +          .then(response => {
Are you going to use this `response`?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/EquipmentDetailsPage/EquipmentDetailsPage.js
> +          .catch(error => {
What about this `error`? Are you going to use it?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/EquipmentDetailsPage/EquipmentDetailsPage.js
> +      .catch(error => {
Another ignored `error`

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/EquipmentDetailsPage/EquipmentDetailsPage.js
> +    // eslint-disable-next-line
What does this comment mean? I'm just kinda confused why this kind of comment is both here and in that other spot I pointed out.

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/InventoryPage/InventoryPage.js
> +          .then(response => {
Is this `response` going to be used?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/InventoryPage/InventoryPage.js
> +          .catch(error => {
What about this `error`?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/InventoryPage/InventoryPage.js
>            .then(reponse => {
What about this `response`?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/InventoryPage/InventoryPage.js
>            .catch(error => {
And this `error`?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/InventoryPage/InventoryPage.js
> +      .catch(error => {
R u going to use this `error`?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +        .then(response => {
Unused `response`?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +        .catch(error => {
Unused `error`?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +          .then(response => {
Unused `response`?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +          .catch(error => {
Unused `error`?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +      .catch(error => {
Unused `error`?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +        .catch(error => {
Unused `error`?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +  // eslint-disable-next-line
Another spot with the confusing comment

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateModelPage/UpdateModelPage.js
> +export default connect(mapStateToProps)(UpdateModelPage);
nit: newline?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateModelPage/UpdateModelPage.js
There's some more unused `response` and `error` in here as well. Are you planning on using them?

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateTypePage/UpdateTypePage.js
FYI, more unused `response` and `error` in here too.

2024-03-04 02:36 UTC, YiJiePV commented on src/Pages/UpdateModelPage/UpdateModelPage.js
I believe this should've worked. Shouldn't this feature work for uploading images from one's computer, or is this part not implemented yet?
![errorpt3](https://github.com/tranleduyan/ETC-Frontend/assets/97055517/0392584b-0aa2-41ae-b598-abf1e4263c8f)
![errorpt1](https://github.com/tranleduyan/ETC-Frontend/assets/97055517/f9ab8e09-e0bb-4782-bd80-36164511c60e)
![errorpt2](https://github.com/tranleduyan/ETC-Frontend/assets/97055517/942e9a1e-e546-4d75-9ec8-d8ba717170b5)

2024-03-04 03:19 UTC, leduyantran commented on src/Components/Cards/InventoryTypeSummaryCard/EquipmentTypeSummaryCard.js
> +  // eslint-disable-next-line
It is to disable the warnings to the unused props that I reserved for RFID implementation later on.

2024-03-04 03:19 UTC, leduyantran commented on src/Components/Cards/InventoryTypeSummaryCard/EquipmentTypeSummaryCard.js
>    // Determine whether to use 'item' or 'items' based on the inventory amount
Done

2024-03-04 03:20 UTC, leduyantran commented on src/Components/Dashboards/AdminDashboard/AdminDashboard.js
> +AdminDashboard.propTypes = {
Done

2024-03-04 03:21 UTC, leduyantran commented on src/Components/Forms/EquipmentForm/EquipmentForm.css
>  }
Done

2024-03-04 03:22 UTC, leduyantran commented on src/Components/InputFields/DatePickerInputField/DatePickerInputField.js
> +DatePickerInputField.defaultProps = {
Done

2024-03-04 03:22 UTC, leduyantran commented on src/Components/InputFields/DatePickerInputField/DatePickerInputField.js
> +export default DatePickerInputField;
Done

2024-03-04 03:22 UTC, leduyantran commented on src/Components/Inventory/EquipmentInventory/EquipmentInventory.css
>  }
Done

2024-03-04 03:23 UTC, leduyantran commented on src/Components/Inventory/ModelInventory/ModelInventory.css
>  }
Done

2024-03-04 03:23 UTC, leduyantran commented on src/Components/Inventory/TypeInventory/TypeInventory.css
>  }
Done

2024-03-04 03:25 UTC, leduyantran commented on src/Pages/EquipmentDetailsPage/EquipmentDetailsPage.js
> +  useEffect(() => {
Done

2024-03-04 03:25 UTC, leduyantran commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.css
> +}
Done

2024-03-04 03:25 UTC, leduyantran commented on src/Pages/UpdateEquipmentPage/index.js
> +export { default } from './UpdateEquipmentPage';
Done

2024-03-04 03:26 UTC, leduyantran commented on src/Pages/UpdateModelPage/UpdateModelPage.css
> +}
Done

2024-03-04 03:27 UTC, leduyantran commented on package.json
It looks normal to me if it is from npm install.

2024-03-04 03:28 UTC, leduyantran commented on package-lock.json
I think you should reclone the repo, maybe it will fix it!

2024-03-04 03:28 UTC, leduyantran commented on src/Components/Cards/EquipmentInventoryCard/EquipmentInventoryCard.css
Done

2024-03-04 03:29 UTC, leduyantran commented on src/Components/Cards/InventoryTypeSummaryCard/EquipmentTypeSummaryCard.js
>    const { className, typeID, typeName, inventoryAmount, reservationAmount, isSelected, OnEquipmentTypeSummaryCardClick } = props;
Yes, it is reserved for rfid implementation when we integrate rfid

2024-03-04 03:30 UTC, leduyantran commented on src/Constants.js
>  export const OPTIONS = {
Done

2024-03-04 03:31 UTC, leduyantran commented on src/Pages/AddToInventoryPage/AddToInventoryPage.js
> +        .then(response => {
Done.

2024-03-04 03:31 UTC, leduyantran commented on src/Pages/EquipmentDetailsPage/EquipmentDetailsPage.js
> +          .then(response => {
Done.

2024-03-04 03:31 UTC, leduyantran commented on src/Pages/EquipmentDetailsPage/EquipmentDetailsPage.js
> +          .catch(error => {
Done

2024-03-04 03:31 UTC, leduyantran commented on src/Pages/EquipmentDetailsPage/EquipmentDetailsPage.js
> +      .catch(error => {
Done

2024-03-04 03:33 UTC, leduyantran commented on src/Pages/EquipmentDetailsPage/EquipmentDetailsPage.js
> +    // eslint-disable-next-line
It is for disabling the props dependencies that react useEffect asked for to have each of the involved components in the dependencies. That is not how useEffect behave with dependencies.

2024-03-04 03:34 UTC, leduyantran commented on src/Pages/InventoryPage/InventoryPage.js
> +          .then(response => {
done

2024-03-04 03:35 UTC, leduyantran commented on src/Pages/InventoryPage/InventoryPage.js
> +          .catch(error => {
done

2024-03-04 03:35 UTC, leduyantran commented on src/Pages/InventoryPage/InventoryPage.js
>            .then(reponse => {
done

2024-03-04 03:35 UTC, leduyantran commented on src/Pages/InventoryPage/InventoryPage.js
>            .catch(error => {
done

2024-03-04 03:35 UTC, leduyantran commented on src/Pages/InventoryPage/InventoryPage.js
> +      .catch(error => {
done

2024-03-04 03:36 UTC, leduyantran commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +        .then(response => {
done.

2024-03-04 03:36 UTC, leduyantran commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +        .catch(error => {
done.

2024-03-04 03:36 UTC, leduyantran commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +          .then(response => {
done.

2024-03-04 03:36 UTC, leduyantran commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +          .catch(error => {
done.

2024-03-04 03:36 UTC, leduyantran commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +      .catch(error => {
done.

2024-03-04 03:36 UTC, leduyantran commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +        .catch(error => {
done.

2024-03-04 03:36 UTC, leduyantran commented on src/Pages/UpdateEquipmentPage/UpdateEquipmentPage.js
> +  // eslint-disable-next-line
see comments

2024-03-04 03:37 UTC, leduyantran commented on src/Pages/UpdateModelPage/UpdateModelPage.js
> +export default connect(mapStateToProps)(UpdateModelPage);
done

2024-03-04 03:38 UTC, leduyantran commented on src/Pages/UpdateModelPage/UpdateModelPage.js
done

2024-03-04 03:39 UTC, leduyantran commented on src/Pages/UpdateModelPage/UpdateModelPage.js
it should work

2024-03-04 03:45 UTC, leduyantran commented on src/Pages/UpdateModelPage/UpdateModelPage.js
Maybe the backend has a regression or it needs an update on google. I will look onto that as soon as i can!

2024-03-06 22:16 UTC, YiJiePV approved these changes
Approved!

2024-03-07 00:34 UTC, merged