ER-75-Skeleton-Sign-In-Page
tranleduyan/ETC-Frontend pull request #7
Opened 2023-11-04 18:23 UTC by tranleduyan

I have implemented the components as well as followed the styling guidelines for responsive designs through each breakpoints (1280x720 and 360x640). The page is scalable and responsive between desktop, tablet, and mobile devices.

2023-11-05 11:09 UTC, mohammedking11-spu approved these changes
Well written the skeleton front end while also sticking to the code convention rules.

2023-11-05 20:25 UTC, YiJiePV requested changes
It looks good to me, and everything is running smoothly so far. Since I'm not an expert in React and stuff, I'm just nitpicking some spots that could use some good coding practices. Once all that's addressed, everything should be good to go. 👍

2023-11-05 20:25 UTC, YiJiePV commented on src/Components/Buttons/LinkButton/LinkButton.css
>  }
nit: I've learned from my internship to always add a newline at the end of every single file, so I'd suggest you do that here too. (GitHub complains about this.) It's also a good habit to have, so I'll also add it to the coding conventions. Here's a link to reasons why this is so: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline.

2023-11-05 20:25 UTC, YiJiePV commented on src/App.js
>  function App() {
nit: it would be nice to have a header comment for this function, even though it is kinda the main function of this file

2023-11-05 20:25 UTC, YiJiePV commented on src/Components/Buttons/StandardButton/StandardButton.css
>  }
nit: a newline is missing here too

2023-11-05 20:25 UTC, YiJiePV commented on src/Components/Buttons/StandardButton/StandardButton.css
nit: it would be nice to have a small comment before each css method, like you did on lines 15 and 23

2023-11-05 20:25 UTC, YiJiePV commented on src/Components/InputFields/StandardTextInputField/StandardTextInputField.css
>  }
nit: newline's missing here too

2023-11-05 20:25 UTC, YiJiePV commented on src/Components/InputFields/StandardTextInputField/StandardTextInputField.css
nit: small comments before each css method?

2023-11-05 20:25 UTC, YiJiePV commented on src/Components/Message/Message.css
nit: small comments before each css method like in the other css files?

2023-11-05 20:25 UTC, YiJiePV commented on src/Pages/SignInPage/SignInPage.css
nit: small method comments here too?

2023-11-05 20:25 UTC, YiJiePV commented on src/Pages/SignInPage/SignInPage.js
>  function SignInPage() {
nit: header comment?

2023-11-05 20:25 UTC, YiJiePV commented on src/Pages/VerificationPage/VerificationPage.css
> +}
nit: newline here as well

2023-11-05 20:25 UTC, YiJiePV commented on src/Pages/VerificationPage/VerificationPage.css
nit: method header comments?

2023-11-05 20:25 UTC, YiJiePV commented on src/Pages/VerificationPage/VerificationPage.js
> +export default VerificationPage
missing ';' after `export default VerificationPage`
nit: newline here too

2023-11-05 20:25 UTC, YiJiePV commented on src/Pages/VerificationPage/index.js
> +export { default } from './VerificationPage';
nit: newline?

2023-11-05 20:25 UTC, YiJiePV commented on src/index.css
>  }
nit: newline missing here too

2023-11-05 21:01 UTC, YiJiePV approved these changes

2023-11-05 21:03 UTC, merged

2023-11-06 06:15 UTC, amansiid commented
Followed code convention