ER-77: Implement Sign In API Calls and Sign Out Functionality
tranleduyan/ETC-Frontend pull request #8
Opened 2023-11-14 10:30 UTC by tranleduyan

I have finished implementing the Sign In API Calls. Upon hitting 'Sign In', all the user data from the response body will be captured and stored for further usage in the application. To test this:
1. Make sure REACT_APP_API_DOMAIN=http://localhost:5000 in your front end .env file is like this.
2. In the backend repo, at line 65, where there is a bcrypt compare password, comment it all out:
        if(!bcrypt.compareSync(password, existUser.ACCOUNT_PASSWORD)) {
            return responseBuilder.BuildResponse(response, 404, {
                message:"Invalid credentials."
            })
        }
This is because we haven't had the sign up yet to have an encrypted password insert to the database to compare the password user input when signing in. If you don't do this, it will return "Invalid credentials." because no account match for that password. Run the backend.
3. The database is having one user account, you can use that email to test. To test redux storage, you can add  Redux DevTools in Chrome Extension to track the Redux. 
4. You should be able to go to the Dashboard page upon sign in with the correct email address in the database. Track the Redux and you should see all the data stored from the response body.

I added all the checks for sign in on the front end as well. I also finished Sign out functionality, which is basically just reset all the user data to null.

2023-11-18 08:37 UTC, YiJiePV commented on package.json
I've encountered this when running `npm install`:
```
up to date, audited 1557 packages in 2s

246 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (2 moderate, 6 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```
Then I found out this using `npm audit`
```
# npm audit report

nth-check  <2.0.1
Severity: high
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix --force`
Will install react-scripts@3.0.1, which is a breaking change
node_modules/svgo/node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/svgo/node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      @svgr/plugin-svgo  <=5.5.0
      Depends on vulnerable versions of svgo
      node_modules/@svgr/plugin-svgo
        @svgr/webpack  4.0.0 - 5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        node_modules/@svgr/webpack
          react-scripts  >=2.1.4
          Depends on vulnerable versions of @svgr/webpack
          Depends on vulnerable versions of resolve-url-loader
          node_modules/react-scripts

postcss  <8.4.31
Severity: moderate
PostCSS line return parsing error - https://github.com/advisories/GHSA-7fh5-64p2-3v2j
fix available via `npm audit fix --force`
Will install react-scripts@3.0.1, which is a breaking change
node_modules/resolve-url-loader/node_modules/postcss
  resolve-url-loader  0.0.1-experiment-postcss || 3.0.0-alpha.1 - 4.0.0
  Depends on vulnerable versions of postcss
  node_modules/resolve-url-loader

8 vulnerabilities (2 moderate, 6 high)

To address all issues (including breaking changes), run:
  npm audit fix --force
```
I had a terrible experience dealing with breaking changes from packages, so I am wondering if there is perhaps a way to remedy this.

2023-11-18 09:04 UTC, YiJiePV commented on src/Pages/SignInPage/SignInPage.js
nit: it would be nice to have a way to just use the ENTER key to continue/confirm input. The UI buttons are really nice and responsive, but I still kept trying to use the ENTER key every time I wanted to confirm input. It's probably just a habit of mine since I'm used to using the keyboard a lot when navigating applications, but this feature would be really nice to have. (Paul may or may not have a similar/different opinion than mine 🤔 )

2023-11-19 03:01 UTC, YiJiePV requested changes
Overall, the code looks pretty good! Again, just some housekeeping things that would be good to keep in mind (Sonarlint's really good at this BTW 😉 ). I didn't point this out in my code reviews, but there are some TODOs left in the code. Just FYI

2023-11-19 03:01 UTC, YiJiePV commented on src/Components/InputFields/StandardTextInputField/StandardTextInputField.js
>  function StandardTextInputField(props) {
It would be nice to have a header comment and some inline comments for this function

2023-11-19 03:01 UTC, YiJiePV commented on src/Components/InputFields/StandardTextInputField/StandardTextInputField.js
> +  const { className, placeholder, name, type, value, onChange, visibility, onKeyDown } = props;
nit: Sonarlint reported this issue for each of the types:

<img width="410" alt="prop-types" src="https://github.com/tranleduyan/ETC-Frontend/assets/97055517/7c323238-85ce-41ec-9374-eeba6803850a">

Here's an example on how to resolve this:

![prop-types-ex](https://github.com/tranleduyan/ETC-Frontend/assets/97055517/ae8b7ba6-6afc-4daf-98fe-af587123d9bc)

And here are links Sonarlint provided with more info:
https://react.dev/reference/react/Component#static-proptypes
https://flow.org/en/docs/react/

I don't know much about React, but I think this practice looks like a good one to adapt.

2023-11-19 03:01 UTC, YiJiePV commented on src/Components/InputFields/StandardTextInputField/StandardTextInputField.js
>             className={`${visibility === false ? `hide ${className}` : className} StandardTextInputField`}
nit: on line 16, you could probably use a simpler expression. Here's more details from Sonarlint:
![ternary-operator](https://github.com/tranleduyan/ETC-Frontend/assets/97055517/69017ab7-68d2-4819-b347-d0f4d9a3dc60)

2023-11-19 03:01 UTC, YiJiePV commented on src/Components/InputFields/StandardTextInputField/StandardTextInputField.js
>             className={`${visibility === false ? `hide ${className}` : className} StandardTextInputField`}
nit: you could separate the nested template literals for more readability. Sonarlint gives more details about this:
![template-litera](https://github.com/tranleduyan/ETC-Frontend/assets/97055517/1edb8b54-3fdd-44f5-b104-923a6b663822)

2023-11-19 03:01 UTC, YiJiePV commented on src/Components/Message/Message.css
>  .Message-Icon {
Is this ruleset going to be completed at some point? Sonarlint's reporting an empty ruleset issue.

2023-11-19 03:01 UTC, YiJiePV commented on src/Components/NavigationBar/NavigationBar.js
> +function NavigationBar(props) {
It would be nice to have a header comment for this function

2023-11-19 03:01 UTC, YiJiePV commented on src/Components/NavigationBar/NavigationBar.js
>    const navigate = useNavigate();
nit: lines 24-50 would be even better condensed. Here's Sonarlint's report:
![redundant](https://github.com/tranleduyan/ETC-Frontend/assets/97055517/7225b1e0-d5e9-4691-a169-062c7dc9692f)
![redundant-1](https://github.com/tranleduyan/ETC-Frontend/assets/97055517/efa87c9b-ad6f-431c-851a-994ce1b8f483)

2023-11-19 03:01 UTC, YiJiePV commented on src/Components/NavigationBar/NavigationBar.js
>    //#endregion
Is there a reason why there's this #endregion comment and its corresponding #region comment?

2023-11-19 03:01 UTC, YiJiePV commented on src/Components/NavigationBar/NavigationBar.js
>    const navigate = useNavigate();
nit: for line 20, it would better to format the inline comment the same way as all the other inline comments, for consistency

2023-11-19 03:01 UTC, YiJiePV commented on src/Components/NavigationBar/NavigationBar.js
> +    props.resetUserData();
nit: this prop isn't in the props validation. Sonarlint's reporting the same issue as the one in the StandardTextInputField.js: `React components should validate prop types (javascript:S6774)`

2023-11-19 03:01 UTC, YiJiePV commented on src/Constants.js
>      key: process.env.REACT_APP_API_KEY,
What is this variable for? A little description would be nice

2023-11-19 03:01 UTC, YiJiePV commented on src/Constants.js
> +export const REGEX = {
A little description for this variable would be nice as well

2023-11-19 03:01 UTC, YiJiePV commented on src/Pages/SignInPage/SignInPage.css
Will the line 39 and 67 rulesets be implemented? Sonarlint's currently reporting empty ruleset issues

2023-11-19 03:01 UTC, YiJiePV commented on src/Pages/SignInPage/SignInPage.js
>  function SignInPage() {
nit: I think it might be best to format line 20 header comment the same way as the ones in the backend repo, unless there's a good reason we're keeping the commenting styles in this repo different from the backend one.

2023-11-19 03:01 UTC, YiJiePV commented on src/Pages/SignInPage/SignInPage.js
nit: lines 53-56 can be reduced to just 1 statement. Sonarlint's description here:
![boolean-exp](https://github.com/tranleduyan/ETC-Frontend/assets/97055517/17755453-27b8-450f-afda-95692847e940)

2023-11-19 03:01 UTC, YiJiePV commented on src/Pages/SignUpPage/SignUpPage.css
> +.SignUpPage-StandardTextInputField {
Will this ruleset be implemented?

2023-11-19 03:01 UTC, YiJiePV commented on src/Pages/SignUpPage/SignUpPage.js
> +// Render the sign up page
nit: same as before: could be formatted like the backend headers

2023-11-19 03:01 UTC, YiJiePV commented on src/Pages/SignUpPage/SignUpPage.js
> +    if(promptState > currentPromptState) {
nit: you can reduce this to a single statement. Same Sonarlint issue as in the SignInPage.js

2023-11-19 03:01 UTC, YiJiePV commented on src/Pages/SignUpPage/SignUpPage.js
> +  const IsValid = () => {
nit: you could refactor/separate the conditional statements in this embedded function. Sonarlint's reporting the issue `Cognitive Complexity of functions should not be too high (javascript:S3776)` (as already explained elsewhere)

2023-11-19 03:01 UTC, YiJiePV commented on src/Pages/SignUpPage/SignUpPage.js
> +    SendVerification: This will generate verification code and call the API to send the generated code to the user's registered email. If every thing is success, navigate to email verification page t
nit: it would be a good idea to format this inline comment the same way as all the other ones

2023-11-19 03:01 UTC, YiJiePV commented on src/Pages/VerificationPage/VerificationPage.js
>  function VerificationPage() {
It would be nice to have a header comment for this function

2023-11-19 03:01 UTC, YiJiePV commented on src/index.js
This file could use some comments

2023-11-20 08:27 UTC, leduyantran commented on src/Components/NavigationBar/NavigationBar.js
>    //#endregion
It is for summary - to be able to collapsed the whole section in IDE so when the file gets larger, we can handle it.

2023-11-20 08:44 UTC, leduyantran commented on src/Pages/SignUpPage/SignUpPage.js
> +// Render the sign up page
I would prefer format this inline comment for the front end since it is mostly only 1 line comment.

2023-11-20 09:09 UTC, leduyantran commented on src/Components/InputFields/StandardTextInputField/StandardTextInputField.js
>  function StandardTextInputField(props) {
done

2023-11-20 09:09 UTC, leduyantran commented on src/Components/InputFields/StandardTextInputField/StandardTextInputField.js
> +  const { className, placeholder, name, type, value, onChange, visibility, onKeyDown } = props;
done

2023-11-20 09:09 UTC, leduyantran commented on src/Components/InputFields/StandardTextInputField/StandardTextInputField.js
>             className={`${visibility === false ? `hide ${className}` : className} StandardTextInputField`}
done

2023-11-20 09:09 UTC, leduyantran commented on src/Components/InputFields/StandardTextInputField/StandardTextInputField.js
>             className={`${visibility === false ? `hide ${className}` : className} StandardTextInputField`}
done

2023-11-20 09:09 UTC, leduyantran commented on src/Components/Message/Message.css
>  .Message-Icon {
It won't (so far), I left it for reminder when doing the responsive. I just deleted it!

2023-11-20 09:10 UTC, leduyantran commented on src/Components/NavigationBar/NavigationBar.js
> +function NavigationBar(props) {
done

2023-11-20 09:10 UTC, leduyantran commented on src/Components/NavigationBar/NavigationBar.js
>    const navigate = useNavigate();
done

2023-11-20 09:10 UTC, leduyantran commented on src/Components/NavigationBar/NavigationBar.js
>    const navigate = useNavigate();
done

2023-11-20 09:10 UTC, leduyantran commented on src/Components/NavigationBar/NavigationBar.js
> +    props.resetUserData();
done

2023-11-20 09:10 UTC, leduyantran commented on src/Constants.js
>      key: process.env.REACT_APP_API_KEY,
done

2023-11-20 09:10 UTC, leduyantran commented on src/Constants.js
> +export const REGEX = {
done

2023-11-20 09:11 UTC, leduyantran commented on src/Pages/SignInPage/SignInPage.css
It won't (so far), I left it for reminder when doing responsive. I just deleted it!

2023-11-20 09:11 UTC, leduyantran commented on src/Pages/SignInPage/SignInPage.js
>  function SignInPage() {
I would prefer format this inline comment for the front end since it is mostly only 1 line comment.

2023-11-20 09:12 UTC, leduyantran commented on src/Pages/SignInPage/SignInPage.js
done

2023-11-20 09:12 UTC, leduyantran commented on src/Pages/SignUpPage/SignUpPage.css
> +.SignUpPage-StandardTextInputField {
It won't (so far), I left it for reminder when working with responsive. I just deleted it!

2023-11-20 09:12 UTC, leduyantran commented on src/Pages/SignUpPage/SignUpPage.js
> +    if(promptState > currentPromptState) {
done

2023-11-20 09:12 UTC, leduyantran commented on src/Pages/SignUpPage/SignUpPage.js
> +  const IsValid = () => {
done

2023-11-20 09:13 UTC, leduyantran commented on src/Pages/SignUpPage/SignUpPage.js
> +    SendVerification: This will generate verification code and call the API to send the generated code to the user's registered email. If every thing is success, navigate to email verification page t
done

2023-11-20 09:13 UTC, leduyantran commented on src/Pages/VerificationPage/VerificationPage.js
>  function VerificationPage() {
done

2023-11-20 09:13 UTC, leduyantran commented on src/index.js
done

2023-11-21 21:15 UTC, mohammedking11-spu approved these changes
After the feedback from Karena and the changes, everything looks nicely written and abides with the code practices standards that we have established. One thing I would appreciate only if you have extra time; but I would personally appreciate if you add a little bit more comments in the css files, but other than that, the comments on other files looks pretty good to me, well done Le!

2023-11-29 07:58 UTC, YiJiePV approved these changes
Looks a lot better now! I agree with Mohammed that perhaps it would be useful to have some more comments in the CSS files, but other than that, it looks pretty solid so far 👍

2023-11-29 17:05 UTC, merged